notifications:
  irc: irc.freenode.org#vdebug
  slack:
    secure: BksygPSsoRfvre27w6XQN9ooKB9C1n83Bw96YurvyDHJ6BYM2Gv9fW1Sj6NHpB8MQkMaJ+9gRiBSflkP+l80t3EXAdStuI/8EM/wZu1ov6bmYT/hYQ8HnULmmPNj8uVzsX13VGEUC/YY4osWuJFM1wh61dStoF+SKrpslqWCV4w=
language: python
python:
- '2.6'
- '2.7'
rvm: 1.9.3
before_install:
- sudo apt-get update && sudo apt-get install vim-gtk php5-cli php5-xdebug
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bundle install
install: pip install -r requirements.txt --use-mirrors
script: bundle exec rake travis
